export const nodes=[
        {
            id: "1",
            jobRequest: "Deploy backend",
            submitted: "2025-06-30",
            status: "In-Process",
            sumbitter: "Alice",
            assigned: "Bob",
            priority: "High",
            dueDate: "2025-07-05",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "$5000",
        },
        {
            id: "2",
            jobRequest: "applied maths",
            submitted: "2025-06-30",
            status: "In-Process",
            sumbitter: "Alice",
            assigned: "Bob",
            priority: "High",
            dueDate: "2025-07-05",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "$5000",
        },
        {
            id: "3",
            jobRequest: "Deploy backend",
            submitted: "2025-06-30",
            status: "In-Process",
            sumbitter: "Alice",
            assigned: "Bob",
            priority: "High",
            dueDate: "2025-07-05",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "$5000",
        },
        {
            id: "4",
            jobRequest: "Deploy backend",
            submitted: "2025-06-30",
            status: "In-Process",
            sumbitter: "Alice",
            assigned: "Bob",
            priority: "High",
            dueDate: "2025-07-05",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "$5000",
        },
        {
            id: "5",
            jobRequest: "Deploy backend",
            submitted: "2025-06-30",
            status: "In-Process",
            sumbitter: "Alice",
            assigned: "Bob",
            priority: "High",
            dueDate: "2025-07-05",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "$5000",
        },
        {
            id: "6",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "7",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "8",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "9",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "10",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "11",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "12",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "13",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "14",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "15",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "16",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "17",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "18",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
        {
            id: "19",
            jobRequest: "",
            submitted: "",
            status: "",
            sumbitter: "",
            assigned: "",
            priority: "",
            dueDate: "",
            // dueDate: new Date("2025-07-05"),
            url: "",
            estValue: "",
        },
    ]
